### PR TITLE
Basic structure

### PR DESCRIPTION
**Pull request by Matiiss**
No `docs` dir, not sure what file to put there...

### CODE REVIEW

**Comment by gresm** [comment]
Maybe this:
```
docs/
  README.md
```

**Comment by novialriptide** [comment]
> Maybe this:
> 
> ```
> docs/
>   README.md
> ```

Nope, that means that GitHub won't be able to find the readme.

LGTM!

**Comment by gresm** [comment]
> > Maybe this:
> > ```
> > docs/
> >   README.md
> > ```
> 
> Nope, that means that GitHub won't be able to find the readme.
> 
Don't remove the main one, github will show the preview of a sub-directory ``readme`` file when entered to the sub-directory.

**Comment by novialriptide** [comment]
> > > Maybe this:
> > > ```
> > > docs/
> > >   README.md
> > > ```
> > 
> > 
> > Nope, that means that GitHub won't be able to find the readme.
> 
> Don't remove the main one, github will show the preview of a sub-directory `readme` file when entered to the sub-directory.

Sorry, I misunderstood. I sent a Discord message in the contributing channel updating the situation.

**Pull request merged**
